version: "3.7"

services:
    frontend:
        container_name: innedu-frontend
        build: ./innedu-platform-fe
        restart: unless-stopped
        ports:
            - "1344:80"

    db:
        container_name: innedu-db
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}

    backend:
        container_name: innedu-backend
        build: ./Backend
        restart: unless-stopped
        ports:
            - "1345:5000"
        depends_on:
            - db
        environment:
            SECRET_KEY: ${SECRET_KEY}
            JWT_SECRET_KEY: ${JWT_SECRET_KEY}
            FRONT_END_URL: ${FRONT_END_URL}
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            FLASK_CONFIG: ${FLASK_CONFIG}
            FLASK_APP: ${FLASK_APP}
            INNEDU_ADMIN: ${INNEDU_ADMIN}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}